
#### Input options

- file_name = this is the name of the excel spreadsheet, use the button to select it on your computer
- num_replicates_A = this is the number of replicates in condition A, i.e. the first set of replicates you specify
- num_replicates_B = this is the number of replicates in condition B, i.e. the second set of replicates
- fit_type = this specifies the type of model that will be fit, can be either linear or cubic
- num_iterations = this specifies the number of iterations for re-sampling (recommended value = 10000)
- bin_choice = this specifies the type of binning, can be either equal or adaptive
- num_bins = this is the number of bins into which the signal-range will be divided, the number of proteins in each bin will depend on the choice of binning (recommended value = 20)
- merge_low = the low-signal bins will be merged so that the lowest one contains atleast this percentage of proteins, applies only if adaptive binning is selected
- merge_high = the high-signal bins will be merged so that the highest one contains atleast this percentage of proteins, applies only if adaptive binning is selected
- fit_quantile = this specifies the quantile that will be used in each bin to select the data points to fit the model (recommended value = 0.5, which represents the median)
- output_id = this specifies the name that will be attached to all output files

