
#### Ouput

GLEE produces a total of 9 output files that deliver all information pertaining to the analysis. In the following notes, "outname" indicates the name that will be attached to all output files, as specified in the input field "output_id". When the analysis is complete, a message will appear below the RUN button indicating the full path to the location of the output files.

**Text files**

outname.DEG.txt

- this is the main output file containing the results of the differential expression test in the last column
- the remaining columns show the mean, standard deviation, p-value and signal-to-noise ratio
- for easier viewing, copy the contents of this file to an excel spreadsheet

outname.selected_points.txt

- this file (created only if binning is chosen) shows the coordinates that were used to fit the specified model

outname.log.txt

- this file tracks the data analysis steps as they are conducted
- shows model-fit statistics (adjusted R-squared) and the number of proteins found to be differentially expressed


**Image files**

- outname.condition-A.png : shows the raw data and model-fit in condition A (the first condition)
- outname.condition-A.siglevel.png : shows the sorted average expression level in condition A
- outname.condition-B.png : shows the raw data and model-fit in condition B (the second condition)
- outname.condition-B.siglevel.png : shows the sorted average expression level in condition B
- outname.stn_distr.png : shows a histogram of the signal-to-noise (STN) distribution
- outname.stn_pvalue.png : shows the STN values against the calculated p-values 
